vivait_email:
    resource: "@VivaitEmailBundle/Resources/config/routing.yml"
    prefix:   /

vivait_crm:
    resource: "@VivaitCRMBundle/Resources/config/routing.yml"
    prefix:   /

vivait_install_successful:
    resource: "@VivaitInstallSuccessfulBundle/Resources/config/routing.yml"
    prefix:   /test

