parameters:
#    vivait_email.example.class: Vivait\EmailBundle\Example

services:
    vivait_email.mailer:
        class: Vivait\EmailBundle\Service\EmailService
        arguments: [@swiftmailer.mailer]
