parameters:
#    vivait_email.example.class: Vivait\EmailBundle\Example

services:
#    vivait_email.example:
#        class: %vivait_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
