vivait_crm_homepage:
    pattern:  /
    defaults: { _controller: VivaitCRMBundle:Home:index }

vivait_crm_customer_list:
    pattern:  /customers
    defaults: { _controller: VivaitCRMBundle:Customer:list }

vivait_crm_customer_add:
    pattern:  /customers/add
    defaults: { _controller: VivaitCRMBundle:Customer:add }

vivait_crm_customer_edit:
    pattern:  /customers/edit/{customer}
    defaults: { _controller: VivaitCRMBundle:Customer:edit }

vivait_crm_customer_delete:
    pattern:  /customers/delete/{customer}
    defaults: { _controller: VivaitCRMBundle:Customer:delete }

vivait_crm_customer_email:
    pattern:  /customers/email/{customer}
    defaults: { _controller: VivaitCRMBundle:Customer:email }
